dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-05/run.sh |
  bash
notifications:
  slack:
    rooms:
     secure: fbsS/HJkIwONV16HnIgQgthkoDkDTHW3v7Z8dgKzH7n6TQoBvipZCCHPK90p8kHzOGWMs5/AzLCzlxy2Yz6nzNSQCrE01+1FknCUWSeK0ABAMa1nB1Xa7xR5NI6rGXTzRE4cy0kahDTst/bSHKlqcGrnwWV6knb0N4L+dj4iw4K6dA+E4hwMPfH8q+6YlChFzxrlC2yhHvEgwlPuQ6Q4IiNCiUbzOAdtMjayRNSOehxp0Nv3URQeRykvlApI2YEI7EQMtcXyfR0+jsSyV27PecmHQ2GTPsTgbrgLOr8Jzb7pWHDWrKCNOWd7W30PZvP1q/HyoQNhSEoJoBEaluljj/cj3fQ4HxeWIBcjYhR5RMlsHySX+0J6xv/EoUT3BaKFJV+wmEqP1HdJcZpvJiyXnCItrCxAQHt09henghNvnZqiyU7g1HLFYHeMqpDUndDIj1JU6saAc1ttnIWiOEGQw23MgrkYlvgLme2PHmoEoFUHMQZAN9+TJ6lZ1vzJM6bxB/UK0R9esiKWdsHJhnzi5z7aWWfTEnTkQPdAZcev/iX5XRW7CpKQvt2o6on1sv2HOAzbeeg/Ik5mh0cOuJyzeWyOjrKlKdcIVMaezTqbQIdxGconh+GpzbeDyJDaS4gyJBZdK5yVoivAPfmBDCw9081eHjhwvF1aPXc4TPkvlY8=
